### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by davidmuc02** [danielpotthast/mvg#2]
I'm having problems installing the plugin.

I can't find the 'mvg' integration in HACS.

Also if I add the sensor to my _configuration.yaml_ and copy all the files to _/config/custom_components/mvg_ I get the following error:
_Platform error 'sensor' from integration 'mvg' - Integration 'mvg' not found._
when refreshing my yaml configurations.

**Comment by danielpotthast** [comment]
Please check the HACS documentation.
You need to add this repository as a custom repository (category: integration) in HACS: https://hacs.xyz/docs/faq/custom_repositories/

**Comment by davidmuc02** [comment]
Thanks, I got it up and running now!
Works like a charm with the custom card from _blackmesa_ I found in the forum:
https://community.home-assistant.io/t/lovelace-munich-public-transport-departure-card/59622/16
