### ISSUE TITLE
Platform error 'sensor' from integration 'mvg' - No module named 'furl'

### ISSUE THREAD

**Issue by joshuajeschek** [danielpotthast/mvg#5]
Hi, after updating to the latest Home Assistant Release (`2024.9.3`), the integration stopped working. Validating the configuration via the Developer Tools gives me the following warning:
```
Platform error 'sensor' from integration 'mvg' - No module named 'furl'
```

**Comment by danielpotthast** [comment]
Thanks for reporting this! I'll take a look into it ~tomorrow~. It's odd how every minor update seems to break the integration.

**Comment by danielpotthast** [comment]
A pre-release update is available. Could you please check if it's working on your instance?

**Comment by beatschubser** [comment]
I had this issue as well, even after reverting to 2024.9.2. I now tried to do a fresh install, but after removing MVG from HACS it's not listed any more at all, so I cannot re-install it.. Edit: I just put everything in the custom_components folder manually and can confirm it's working again 👍 Would be nice to have it in HACS again, though 😉 Thanks for this integration btw., it's super useful!

**Comment by danielpotthast** [comment]
> I had this issue as well, even after reverting to 2024.9.2. I now tried to do a fresh install, but after removing MVG from HACS it's not listed any more at all, so I cannot re-install it..

Did you add the custom repository in HACS?

![image](https://github.com/user-attachments/assets/40294f5f-a808-4e1f-b0ab-f7480fa610a0)

**Comment by beatschubser** [comment]
Yes, I added https://github.com/danielpotthast/mvg there, but that didn't help.

**Comment by joshuajeschek** [comment]
Using version 1.1.1 resolved the issue for me. Thanks!

**Comment by danielpotthast** [comment]
> Yes, I added https://github.com/danielpotthast/mvg there, but that didn't help.

That's odd. I didn't make any changes, yet I was able to reinstall the current version successfully. 🤔

**Comment by beatschubser** [comment]
After adding it manually to the folder it showed up for installation in HACS again 🤷‍♂️ Is it safe to update to 2024.9.3 now?

**Comment by danielpotthast** [comment]
> After adding it manually to the folder it showed up for installation in HACS again 🤷‍♂️ Is it safe to update to 2024.9.3 now?

Yes, no issues for me so far 👍
