### ISSUE TITLE
Entität nicht verfügbar: sensor.xyz

### ISSUE THREAD

**Issue by beatschubser** [danielpotthast/mvg#7]
Hi,

since yesterday the integration stopped working again, only showing "Entität nicht verfügbar: sensor.xyz" in the frontend. I haven't changed the configuration, maybe it's related to a HA-update?

```
Core: 2024.10.2
Supervisor: 2024.10.2
Operating System: 13.2
Frontend: 20241002.3
```

**Comment by danielpotthast** [comment]
Thank you for reporting. It appears that MVG has updated their API again, which is likely causing the issue.

**Comment by danielpotthast** [comment]
This should be working again with version `1.1.2` :)

**Comment by beatschubser** [comment]
... and it does :) Awesome, thank you for the quick fix!
